// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBejuM90iA5HqKuSHKUls-fUW3OQDv400c',
    appId: '1:1079419670421:web:5a6c0db4ec44a1e4da309c',
    messagingSenderId: '1079419670421',
    projectId: 'apponsr-bcf81',
    authDomain: 'apponsr-bcf81.firebaseapp.com',
    storageBucket: 'apponsr-bcf81.appspot.com',
    measurementId: 'G-4RDHNE2WXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwgmF4A7CJXNgCoFXmDDSljlnsQmlXZM',
    appId: '1:1079419670421:android:6bc001cfc0e8cf30da309c',
    messagingSenderId: '1079419670421',
    projectId: 'apponsr-bcf81',
    storageBucket: 'apponsr-bcf81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy4rZ40nKMDzxqs84CbdhokPis7tIST7Q',
    appId: '1:1079419670421:ios:94576c4d5820cc38da309c',
    messagingSenderId: '1079419670421',
    projectId: 'apponsr-bcf81',
    storageBucket: 'apponsr-bcf81.appspot.com',
    iosBundleId: 'com.example.onsr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy4rZ40nKMDzxqs84CbdhokPis7tIST7Q',
    appId: '1:1079419670421:ios:94576c4d5820cc38da309c',
    messagingSenderId: '1079419670421',
    projectId: 'apponsr-bcf81',
    storageBucket: 'apponsr-bcf81.appspot.com',
    iosBundleId: 'com.example.onsr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBejuM90iA5HqKuSHKUls-fUW3OQDv400c',
    appId: '1:1079419670421:web:4a963201e9afdf51da309c',
    messagingSenderId: '1079419670421',
    projectId: 'apponsr-bcf81',
    authDomain: 'apponsr-bcf81.firebaseapp.com',
    storageBucket: 'apponsr-bcf81.appspot.com',
    measurementId: 'G-E7MJGSM3ZS',
  );
}
